### ISSUE TITLE
Use in Class?

### ISSUE THREAD

**Issue by Luc45** [lucatume/wp-routes#2]
Hey, is it possible to use klein_respond() in a class?

Something like this:
`klein_respond( 'GET', '/checkoutflow/ja_tenho_conta_sou_novo', [$this, 'some_class_function'] );`

Similar to add_action()?
`add_action( 'plugins_loaded', array($this, 'some_class_function') );`

**Comment by Luc45** [comment]
Nevermind, got it:
`klein_respond( 'GET', '/checkoutflow/ja_tenho_conta_sou_novo', $WooCheckoutFlow->ja_tenho_conta_sou_novo() );`

**Comment by Luc45** [comment]
Actually, I didn't get it. When I use like the example above, `klein_Request $request, klein_Response $response` don't get through to `ja_tenho_conta_sou_novo()`

**Comment by lucatume** [comment]
HI,

If you are using this code:

```php
klein_respond( 
    'GET', 
    '/checkoutflow/ja_tenho_conta_sou_novo', 
    $WooCheckoutFlow->ja_tenho_conta_sou_novo() 
);
```
To handle the request than that's not working as you are invoking the `$WooCheckoutFlow->ja_tenho_conta_sou_novo()` immediately, while registering the handler.
The correct code is
```php
klein_respond( 
    'GET', 
    '/checkoutflow/ja_tenho_conta_sou_novo', 
    [ $WooCheckoutFlow, 'ja_tenho_conta_sou_novo' ] 
);
```
