### ISSUE TITLE
Packagist?

### ISSUE THREAD

**Issue by Luc45** [lucatume/wp-routes#3]
Hi Luca,

Do you plan to release this as a packagist package?

Best,
Lucas

**Comment by lucatume** [comment]
Not really. I'd like to rework this a bit really to make it a bit more modern: e.g. removing the dependency on the PHP 5.2-compatible version of klein and leverage the concept of the `App` object more basing it on DI52.
It can still be required as a Composer dependency though, it's sufficient to define [a repository in the `composer.json` file](https://getcomposer.org/doc/05-repositories.md#vcs).

**Comment by Luc45** [comment]
Great idea, totally forgot about `repositories`!

Closing this issue, thanks!
